/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** アクセス可能なペット一覧を取得する（所有 + 共有） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Pet"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** ペットを登録する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PetInput"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        /** ペットを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** ペットを削除する */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** ペットを更新する */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PetInput"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/pets/{petId}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        /** 思い出一覧を取得する（新しい順） */
        get: {
            parameters: {
                query?: {
                    category?: components["schemas"]["MemoryCategory"];
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Memory"][];
                            total: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** 思い出を記録する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryInput"];
                };
            };
            responses: {
                /** @description 記録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Memory"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/memories/{memoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 思い出を削除する */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                    memoryId: components["parameters"]["memoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/feelings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        /** 気持ち記録一覧を取得する */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Feeling"][];
                            total: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 気持ちを記録する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeelingInput"];
                };
            };
            responses: {
                /** @description 記録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Feeling"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        /** 予定一覧を取得する（日付昇順） */
        get: {
            parameters: {
                query?: {
                    /** @description 開始日（ISO 8601） */
                    from?: string;
                    /** @description 終了日（ISO 8601） */
                    to?: string;
                };
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Schedule"][];
                            total: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 予定を追加する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScheduleInput"];
                };
            };
            responses: {
                /** @description 追加成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Schedule"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
                scheduleId: components["parameters"]["scheduleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 予定を削除する */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                    scheduleId: components["parameters"]["scheduleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 招待リンクを生成する（OWNER のみ） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 生成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        /** メンバー一覧を取得する（OWNER のみ） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["PetMember"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
                memberId: components["parameters"]["memberId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** メンバーを除外する（OWNER のみ） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                    memberId: components["parameters"]["memberId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 除外成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invite/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 招待を受け入れてメンバーとして参加する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        token: string;
                    };
                };
            };
            responses: {
                /** @description 参加成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            petId: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description 招待リンクの有効期限切れ */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/photobook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        /** 月次フォトブックを PDF で取得する（Sora+ のみ） */
        get: {
            parameters: {
                query?: {
                    year?: number;
                    month?: number;
                };
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF 生成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                402: components["responses"]["PaymentRequired"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{petId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                petId: components["parameters"]["petId"];
            };
            cookie?: never;
        };
        /** 年次メモリーレポートを PDF で取得する（Sora+ のみ） */
        get: {
            parameters: {
                query?: {
                    /** @description 対象年（省略時は前年） */
                    year?: number;
                };
                header?: never;
                path: {
                    petId: components["parameters"]["petId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF 生成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                402: components["responses"]["PaymentRequired"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在のプランを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plan: components["schemas"]["BillingPlan"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Checkout セッションを作成する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        interval: components["schemas"]["CheckoutInterval"];
                    };
                };
            };
            responses: {
                /** @description セッション作成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Customer Portal セッションを作成する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description セッション作成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Webhook イベントを受信する（Stripe からのみ呼ばれる） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 受信成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{memoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memoryId: string;
            };
            cookie?: never;
        };
        /** 公開思い出データを取得する（認証不要） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareMemory"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/og": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OGP / マイルストーン記念カード画像を生成する（認証不要） */
        get: {
            parameters: {
                query?: {
                    type?: "memory" | "milestone";
                    title?: string;
                    date?: string;
                    petName?: string;
                    photoUrl?: string;
                    /** @description milestone タイプ時の記念日ラベル（例: 100日目） */
                    label?: string;
                    /** @description milestone タイプ時の絵文字 */
                    emoji?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 画像生成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push 購読情報を登録する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        endpoint: string;
                        p256dh: string;
                        auth: string;
                    };
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** デイリーリマインダー Push を送信する（Cron のみ） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 送信成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/annual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 年次レポート完成 Push を送信する（Cron のみ） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 送信成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Species: "dog" | "cat" | "rabbit" | "bird" | "other";
        /** @enum {string} */
        Gender: "male" | "female" | "unknown";
        /** @enum {string} */
        PetStatus: "alive" | "rainbow_bridge";
        /**
         * @description owner = ペット登録者, member = 招待で参加した家族
         * @enum {string}
         */
        PetRole: "owner" | "member";
        Pet: {
            /** Format: uuid */
            id: string;
            name: string;
            nickname?: string;
            species?: components["schemas"]["Species"];
            breed?: string;
            /** Format: date */
            birthDate?: string;
            /**
             * Format: date
             * @description ペットを迎えた日
             */
            broughtAt?: string;
            gender?: components["schemas"]["Gender"];
            /** Format: uri */
            photoUrl?: string;
            personality?: string;
            favorites?: string;
            status: components["schemas"]["PetStatus"];
            role: components["schemas"]["PetRole"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PetInput: {
            name: string;
            nickname?: string;
            species?: components["schemas"]["Species"];
            breed?: string;
            /** Format: date */
            birthDate?: string;
            /** Format: date */
            broughtAt?: string;
            gender?: components["schemas"]["Gender"];
            /** Format: uri */
            photoUrl?: string;
            personality?: string;
            favorites?: string;
            status?: components["schemas"]["PetStatus"];
        };
        /** @enum {string} */
        MemoryCategory: "trip" | "daily" | "hospital" | "trimming" | "anniversary" | "other";
        /** @enum {string} */
        MoodTag: "happy" | "calm" | "worried" | "fun" | "loving";
        Memory: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            /** Format: date */
            date: string;
            category: components["schemas"]["MemoryCategory"];
            moodTag?: components["schemas"]["MoodTag"];
            photoUrls: string[];
            /** Format: date-time */
            createdAt: string;
        };
        MemoryInput: {
            title: string;
            description?: string;
            /** Format: date */
            date: string;
            category?: components["schemas"]["MemoryCategory"];
            moodTag?: components["schemas"]["MoodTag"];
            photoUrls?: string[];
        };
        /** @enum {string} */
        FeelingTag: "happy" | "calm" | "fun" | "worried" | "loving" | "sad" | "hard" | "numb";
        Feeling: {
            /** Format: uuid */
            id: string;
            tag: components["schemas"]["FeelingTag"];
            memo?: string;
            /** Format: date */
            date: string;
            /** Format: date-time */
            createdAt: string;
        };
        FeelingInput: {
            tag: components["schemas"]["FeelingTag"];
            memo?: string;
            /** Format: date */
            date: string;
        };
        /** @enum {string} */
        ScheduleType: "hospital" | "trimming" | "vaccine" | "anniversary" | "other";
        Schedule: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ScheduleType"];
            title: string;
            /** Format: date */
            date: string;
            memo?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ScheduleInput: {
            type: components["schemas"]["ScheduleType"];
            title: string;
            /** Format: date */
            date: string;
            memo?: string;
        };
        PetMember: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["PetRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        /** @enum {string} */
        BillingPlan: "FREE" | "PLUS";
        /** @enum {string} */
        CheckoutInterval: "month" | "year";
        ShareMemory: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            /** Format: date */
            date: string;
            photoUrls: string[];
            petName: string;
            /** Format: uri */
            petPhotoUrl?: string;
        };
        ProblemDetail: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description 認証が必要 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description リソースが存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Sora+ プランが必要 */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description バリデーションエラー */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        petId: string;
        memoryId: string;
        scheduleId: string;
        memberId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
